### ISSUE TITLE
Consider using OCaml naming conventions for functions

### ISSUE THREAD

**Issue by darioteixeira** [besport/ocaml-jwt#1]
I realise this library is probably still a work-in-progress, but after playing with it a bit, the one thing that immediately comes to mind is that many function names do not follow OCaml conventions. Examples:

 * `algorithm_of_str`: should be `algorithm_of_string`
 * `algorithm_to_str`: should be `string_of_algorithm`

Other than that, cheers for making it publicly available!

**Comment by dannywillems** [comment]
Thanks for your comment. I agree with you. It will be changed.

It will be released very soon.

**Comment by dannywillems** [comment]
@darioteixeira OCaml convention is now used.

**Comment by dannywillems** [comment]
@darioteixeira I close because I think it's fixed.
