### ISSUE TITLE
Adding JWK

### ISSUE THREAD

**Issue by ulrikstrid** [besport/ocaml-jwt#23]
I'm creating a OIDC provider and has written some code to generate JWK(s) that I can use together with this library, would you be willing to take that code as a contribution?

I also have a "end-to-end" test that exercise both parts together that I would love to contribute.

**Comment by dannywillems** [comment]
Feel free to make a PR.

Sorry for the delay.

**Comment by ulrikstrid** [comment]
Hey, I actually had some increased needs other than what this library provides so I created a "full" JOSE implementation.
It can be found here: https://github.com/ulrikstrid/reason-jose
and on opam under the name jose.
